### ISSUE TITLE
First branch of tree is not displayed

### ISSUE THREAD

**Issue by jg2703** [hungrymedia/interactive-decision-tree#15]
Hi @hungrymedia 
I appreciate you're not supporting this module any more, but was just hoping you could help out - the XML doesn't display for the first branch, and there's nothing to show why. Just looking at the CSS it gives `branch-1-1` the `active` class first, without displaying the first question. I'm running it alongside Bootstrap using jQuery 2.2.4 but even reverting to the older jQuery seems to make no difference.
Is this a known problem?
Thanks in advance

**Comment by hungrymedia** [comment]
@jg2703 Are you willing to share your XML file? It seems like something must be amiss, there.

**Comment by jg2703** [comment]
@hungrymedia see my XML file on the link below. Many thanks for your help and quick response![XML file](http://cmt.joelgdesign.co.uk/xml/tree1488742438.xml)

**Comment by jg2703** [comment]
@hungrymedia try again... http://cmt.joelgdesign.co.uk/xml/tree1488742438.xml

**Comment by hungrymedia** [comment]
Try moving branch 1 to be the first branch within the XML

**Comment by jg2703** [comment]
@hungrymedia seems to have worked, thanks. Any reason why it would have put it there?
Thanks
